[files]
recent_files=/home/eldermf/.config/bspwm/bspwmrc;/home/eldermf/Downloads/bspwm-master/000-installing-yay.sh;/home/eldermf/Downloads/NerdFont-Cheat-Sheet-main/updateScript.js;/home/eldermf/Downloads/NerdFont-Cheat-Sheet-main/nerdfont.txt;/home/eldermf/.viminfo;/run/user/1000/gvfs/mtp:host=Xiaomi_POCO_X6_Pro_5G_FQPVR4B6MN8X55VS/Divisão interna de armazenamento/Download/pacman.conf;/run/user/1000/gvfs/mtp:host=Xiaomi_POCO_X6_Pro_5G_FQPVR4B6MN8X55VS/Divisão interna de armazenamento/Diary/2024/08/31.md;/home/eldermf/Downloads/Rascunho;/run/media/eldermf/virus_900/Documentos/Cursos-Dicas-Livros-Tutoriais/Linux/Tutoriais.txt;/home/eldermf/.config/bspwm/sxhkdrc;
recent_projects=
current_page=3
FILE_NAME_0=1569;Sh;0;EUTF-8;1;1;0;%2Fhome%2Feldermf%2FDownloads%2Fbspwm-master%2F010-basics-files.sh;0;4
FILE_NAME_1=1129;Sh;0;EUTF-8;1;1;0;%2Fhome%2Feldermf%2FDownloads%2Fbspwm-artix%2F010-xorg-audio-mpd.sh;0;4
FILE_NAME_2=535;Sh;0;EUTF-8;1;1;0;%2Fhome%2Feldermf%2FDownloads%2Fbspwm-master%2F040-artix_repos.sh;0;4
FILE_NAME_3=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Feldermf%2FDownloads%2Fbspwm-master%2F020-basics-copy_etc_files.sh;0;4

[project]
session_file=
project_file_path=

[geany]
treeview_position=156
msgwindow_position=472
geometry=1930;54;1332;696;1;
sidebar_page=0

[VTE]
last_dir=/home/eldermf/.local/bin

[search]
find_all_expanded=false
replace_all_expanded=true
position_find_x=646
position_find_y=441
position_replace_x=855
position_replace_y=535
position_fif_x=675
position_fif_y=205

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
